// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyykSTO6rosal8EUGfQEmXpZMOLfQFIdw',
    appId: '1:813214746107:web:ca791d6a7b68f38da5775e',
    messagingSenderId: '813214746107',
    projectId: 'photo-coach',
    authDomain: 'photo-coach.firebaseapp.com',
    storageBucket: 'photo-coach.appspot.com',
    measurementId: 'G-FMQNCDMX0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUyoW3ms4blwtIRLHIEjC7iZ7SrWyzguA',
    appId: '1:813214746107:android:b7b2673599d0d191a5775e',
    messagingSenderId: '813214746107',
    projectId: 'photo-coach',
    storageBucket: 'photo-coach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9WhTJKyp56V0-N9JSEkH_CsVlCO4vfBk',
    appId: '1:813214746107:ios:6e27a92901e1219aa5775e',
    messagingSenderId: '813214746107',
    projectId: 'photo-coach',
    storageBucket: 'photo-coach.appspot.com',
    iosBundleId: 'com.example.photoCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9WhTJKyp56V0-N9JSEkH_CsVlCO4vfBk',
    appId: '1:813214746107:ios:b5c35a2fcb382fd0a5775e',
    messagingSenderId: '813214746107',
    projectId: 'photo-coach',
    storageBucket: 'photo-coach.appspot.com',
    iosBundleId: 'com.example.photoCoach.RunnerTests',
  );
}
